/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oV1ZfjYSHBy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { CodeIcon } from "lucide-react"
import Header from "../header/Header"
import { stacks } from "../skill/skills"
import { aboutMe, certificates, educations, experiences } from "./Experience"
import Footer from "../footer/footer"

export function About() {
  return (
    <div className="w-full">
      <Header />
      <section className="bg-muted py-12 md:py-24">
        <div className="flex flex-col items-center justify-center gap-6 px-4 md:flex-row md:gap-10">
          <div className="flex-shrink-0">
            <Avatar className="h-32 w-32 md:h-40 md:w-40">
              <AvatarImage src={aboutMe.image} />
              <AvatarFallback>SA</AvatarFallback>
            </Avatar>
          </div>
          <div className="text-center md:text-left">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">{aboutMe.fullname}</h1>
            <p className="mt-2 text-muted-foreground md:text-xl">{aboutMe.role}</p>
            <p className="mt-2 font-extrabold badge rounded uppercase font-mono">{`${aboutMe.experience} years Industry Experience`}</p>
            <p className="mt-4 max-w-[600px] text-muted-foreground md:text-lg">{aboutMe.description}
            </p>
            <div className="mt-6 flex justify-center md:justify-start">
              <Button className="mr-4">View Resume</Button>
              <Button variant="secondary">Contact Me</Button>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24">
        <div className="grid gap-12 px-4 md:grid-cols-2 md:gap-16 place-items-stretch place-content-center">
          <div>
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Mission & Vision</h2>
            <div className="mt-4 grid grid-cols-2 gap-4 place-content-stretch">
                  <div className="rounded-lg bg-muted p-4 text-center">
                  <CodeIcon className="mx-auto h-8 w-8 text-primary" />
                  <p className="mt-2 font-medium">{aboutMe.missionVision}</p>
                </div>
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Personal Interests</h2>
            <div className="mt-4 space-y-4">
                <div >
                <h3 className="text-lg font-medium">{aboutMe.interest}</h3>
                <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl mt-5 mb-3">Interested Industries</h2>
                {aboutMe.industry.map((item, index: number) => (
                  <ol key={index} className="font-bold">
                    <li>{item}</li>
                  </ol>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24">
        <div className="grid gap-12 px-4 md:grid-cols-2 md:gap-16 place-items-stretch place-content-center">
          <div>
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Skills</h2>
            <div className="mt-4 grid grid-cols-2 gap-4">
              {stacks.map((stack) => (
                  <div key={stack.id} className="rounded-lg bg-muted p-4 text-center">
                  <CodeIcon className="mx-auto h-8 w-8 text-primary" />
                  <p className="mt-2 font-medium">{stack.stack}</p>
                </div>
              ))}
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Experience</h2>
            <div className="mt-4 space-y-4">
              { experiences.map((experience) => (
                <div key={experience.id}>
                <h3 className="text-lg font-medium">{`${experience.role}, ${experience.organization}`}.</h3>
                <p className="text-muted-foreground">{`${experience.startYear} - ${experience.endYear}`}</p>
                <p className="mt-2 text-muted-foreground">{experience.description}
                </p>
              </div>
              ))}
            </div>
          </div>
        </div>
      </section>
      <section className="bg-muted py-12 md:py-24">
        <div className="grid gap-12 px-4 md:grid-cols-2 md:gap-16">
          <div>
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Education</h2>
            <div className="mt-4 space-y-4">
              {educations.map((education) => (
                <div key={education.id}>
                <h3 className="text-lg font-medium">{education.role}</h3>
                <p className="text-muted-foreground">{`${education.organization}, ${education.startYear}`}</p>
                <p className="mt-2 text-muted-foreground">
                  {education.description}
                </p>
              </div>
              ))}
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Certifications</h2>
            <div className="mt-4 space-y-4">
              {certificates.map((certificate) => (
                <div key={certificate.id}>
                <h3 className="text-lg font-medium">{certificate.role}</h3>
                <p className="text-muted-foreground">{`${certificate.organization}, ${certificate.startYear}`}</p>
                <p className="mt-2 text-muted-foreground">
                 {certificate.description}
                </p>
              </div>
              ))}
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  )
}
